2019-11-28 22:46:05,699 ERROR: Exception on /search [GET] [in /Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/Users/rosalindbenoit/src/quickgig/app/main/routes.py", line 21, in before_first_request
    user_datastore.find_or_create_role(name='admin', description='Administrator')
NameError: name 'user_datastore' is not defined
2019-12-06 18:07:39,759 INFO: QuickGig startup [in /Users/rosalindbenoit/src/quickgig/app/__init__.py:80]
2019-12-06 18:09:01,135 ERROR: Exception on /edit/15 [POST] [in /Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rosalindbenoit/src/quickgig/app/main/routes.py", line 80, in edit_gig
    return redirect(url_for('main.edit_gig.html'))
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.edit_gig.html'. Did you mean 'main.edit_gig' instead?
2019-12-06 18:09:26,966 ERROR: Exception on /edit/15 [POST] [in /Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rosalindbenoit/src/quickgig/app/main/routes.py", line 80, in edit_gig
    return redirect(url_for('main.edit_gig.html'))
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.edit_gig.html'. Did you mean 'main.edit_gig' instead?
2019-12-06 18:37:51,186 ERROR: Exception on /edit/15 [POST] [in /Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rosalindbenoit/src/quickgig/app/main/routes.py", line 80, in edit_gig
    return redirect(url_for('main.edit_gig.html'))
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/rosalindbenoit/src/quickgig/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.edit_gig.html'. Did you mean 'main.edit_gig' instead?
